# Backstage override configuration for your local development environment
app:
  listen:
    host: 0.0.0.0

auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        ## uncomment if using GitHub Enterprise
        # enterpriseInstanceUrl: ${AUTH_GITHUB_ENTERPRISE_INSTANCE_URL}
        signIn:
          resolvers:
            # Matches the GitHub username with the Backstage user entity name.
            # See https://backstage.io/docs/auth/github/provider#resolvers for more resolvers.
            - resolver: usernameMatchingUserEntityName


catalog:
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: /app/backstage/catalog/entities/users.yaml
      rules:
        - allow: [User]

    - type: file
      target: /app/backstage/catalog/entities/groups.yaml
      rules:
        - allow: [Group]

    - type: url
      target: https://github.com/saagarsvs05/backstage-software-template/blob/main/python-app/template.yaml
      rules:
        - allow: [Template]
    
    - type: url
      target: https://github.com/saagarsvs05/backstage-software-template/blob/main/nodejs-app/template.yaml
      rules:
        - allow: [Template]

    - type: url
      target: https://github.com/saagarsvs05/backstage-software-template/blob/main/react-app/template.yaml
      rules:
        - allow: [Template]

    - type: url
      target: https://github.com/saagarsvs05/backstage-software-template/blob/main/dotnet-app/template.yaml
      rules:
        - allow: [Template]
    - type: url
      target: https://github.com/saagarsvs05/backstage-software-template/blob/main/angular-app/template.yaml
      rules:
        - allow: [Template]
techdocs:
  builder: 'local'
  publisher:
    type: 'local'
  generator:
    runIn: local


integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/integrations/github/locations#configuration
      token: ${GITHUB_TOKEN}

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://backstage--devopsautomation-b58fc1-zoftbowd.hcp.eastus2.azmk8s.io
          name: backstage-aks
          authProvider: 'azure'
          skipTLSVerify: false
          skipMetricsLookup: false
