apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: development
  description: Development Team 
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: devteam@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Fluffy&backgroundType=>
  children: []
